# Simple example demonstrating tred interface
This is a hacky 20 minute notebook demonstrating deadpan basic functionalities
in `tred`. It unfortunately, at the moment, does not cover all of the public 
functionality. 

In [1]:
import numpy as np

import tred
from tred import display_tensor_facewise as disp

First we will create some dummy data

In [2]:
# let's use a numpy rng
RNG = np.random.default_rng(seed=1234)

# then we will generate some dummy data
n, p, t = 3, 4, 2
X = RNG.random(size=(n, p, t))

Let's quickly view our data using the `display_tensor_facewise` function, which we imported as `disp`. Note: this looks a bit nicer than calling `print(X)`

In [3]:
disp(X)

Tensor with dimensions (3, 4, 2)
[[[0.97669977 0.92324623 0.31909706 0.24176629]
  [0.96407925 0.44100612 0.8636213  0.67488131]
  [0.7357577  0.17206618 0.06013866 0.67123802]]

 [[0.38019574 0.26169242 0.11809123 0.31853393]
  [0.2636498  0.60987081 0.86375767 0.65987435]
  [0.22275366 0.87041497 0.68368891 0.61101798]]]


Let's get the tsvdm decomposition first, using the `tsvdm` function

In [4]:
# so, first we can use tred's tsvdm decomposition
U, S, V = tred.tsvdm(X)

In [5]:
disp(U)

Tensor with dimensions (3, 3, 2)
[[[ 0.17155477 -0.03254445 -0.56750142]
  [ 0.77376295 -0.77505461  0.24995519]
  [ 1.00613179  0.03661673  0.27647539]]

 [[ 0.49697207  1.1805333   0.08253392]
  [ 0.21963571 -0.04814225 -0.82918402]
  [-0.25364858  0.03023034  0.91905817]]]


In [6]:
disp(S)

Tensor with dimensions (3, 4, 2)
[[[ 2.49071429  0.          0.          0.        ]
  [ 0.          0.95133804  0.          0.        ]
  [ 0.          0.          0.33545775  0.        ]]

 [[ 1.2959226   0.          0.          0.        ]
  [ 0.         -0.06058465  0.          0.        ]
  [ 0.          0.          0.10984777  0.        ]]]


In [7]:
disp(V)

Tensor with dimensions (4, 4, 2)
[[[ 0.72770621 -0.26446627 -0.16542903 -0.41692012]
  [-0.15139073 -0.0209886  -0.29168408  0.60752868]
  [-0.01705587 -0.61095445  0.23509181  0.09922585]
  [ 0.39762985 -0.16678187  0.60880143  0.52113841]]

 [[ 0.0244148   0.95052807 -0.33592066 -0.4270477 ]
  [ 0.84344351  0.65517601  0.43308422  0.44074385]
  [ 0.69522119 -0.36615433 -0.96110795  0.14212615]
  [ 0.30626555 -0.2484096   0.48735324 -0.8825139 ]]]


In [8]:
# note: the V tensor is not transposed!
# in order to do a facewise transpose - use numpy
Vt = V.transpose(1, 0, 2)

In [9]:
disp(Vt)

Tensor with dimensions (4, 4, 2)
[[[ 0.72770621 -0.15139073 -0.01705587  0.39762985]
  [-0.26446627 -0.0209886  -0.61095445 -0.16678187]
  [-0.16542903 -0.29168408  0.23509181  0.60880143]
  [-0.41692012  0.60752868  0.09922585  0.52113841]]

 [[ 0.0244148   0.84344351  0.69522119  0.30626555]
  [ 0.95052807  0.65517601 -0.36615433 -0.2484096 ]
  [-0.33592066  0.43308422 -0.96110795  0.48735324]
  [-0.4270477   0.44074385  0.14212615 -0.8825139 ]]]


Now, let's use the tensor decomposition using the `tpca` object. Revise some basics of object oriented programming and scikit-learn's interface if you are coming from R.

In [10]:
# first, create a transformer object
tpca1 = tred.TPCA()

There's two ways to do this:

In [11]:
# 1. you explicitly fit your tpca object, and then transform your data
# here's what happens if you call transform by itself!
X_transformed_1 = tpca1.transform(X)

NotFittedError: This TPCA instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
disp(X)

Tensor with dimensions (3, 4, 2)
[[[0.97669977 0.92324623 0.31909706 0.24176629]
  [0.96407925 0.44100612 0.8636213  0.67488131]
  [0.7357577  0.17206618 0.06013866 0.67123802]]

 [[0.38019574 0.26169242 0.11809123 0.31853393]
  [0.2636498  0.60987081 0.86375767 0.65987435]
  [0.22275366 0.87041497 0.68368891 0.61101798]]]


In [ ]:
# so, we need to fit the tpca object first - then call transform!
tpca1.fit(X)
X_transformed_1 = tpca1.transform(X)

In [ ]:
# 2. or, we can simply just call fit_transform!
# note: this produces the same result to machine precision, but not identical
# see the tred library implementation for more details
tpca2 = tred.TPCA()
X_transformed_2 = tpca2.fit_transform(X)

In [ ]:
# the size of this is n rows by min(n, p) columns
X_transformed_1

array([[ 5.68460112e-01,  5.11808598e-01, -1.54348130e-01,
        -6.89881787e-02,  1.42247325e-16, -2.77555756e-17],
       [-6.66509430e-03, -5.59723785e-01, -1.17834904e-01,
         1.40461250e-01, -1.70870262e-16, -2.77555756e-17],
       [-5.61795018e-01,  4.79151878e-02,  2.72183034e-01,
        -7.14730711e-02,  1.73472348e-17,  1.80411242e-16]])

In [ ]:
# NOTE: this is the same as the array above - to machine precision
# some numbers LOOK different, but you'll see that they are tiny and
# are actually meant to be 0's
X_transformed_2

array([[ 5.68460112e-01,  5.11808598e-01, -1.54348130e-01,
        -6.89881787e-02, -6.00850325e-17,  5.86791256e-17],
       [-6.66509430e-03, -5.59723785e-01, -1.17834904e-01,
         1.40461250e-01, -6.00850325e-17,  5.86791256e-17],
       [-5.61795018e-01,  4.79151878e-02,  2.72183034e-01,
        -7.14730711e-02, -6.00850325e-17,  5.86791256e-17]])

We can use the fitted objects to transform out of bag data

In [ ]:
new_obs = RNG.random(size=(1, p, t))

In [ ]:
disp(new_obs)

Tensor with dimensions (1, 4, 2)
[[[0.06013731 0.43895163 0.00313229 0.85849044]]

 [[0.97776927 0.53259502 0.25126711 0.42529835]]]


In [ ]:
# make sure you do not call anything with 'fit'!
# that will change the tpca loadings
tpca1.transform(new_obs)

array([[-0.13546024,  0.34661962,  0.39718925, -0.55304217,  0.95086191,
         0.07885213]])